//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgentApplication.AccommodationUnitService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.projectXml.com/accommodationUnit", ConfigurationName="AccommodationUnitService.AccommodationUnitPort")]
    public interface AccommodationUnitPort {
        
        // CODEGEN: Generating message contract since the operation getAccommodationUnits is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AgentApplication.AccommodationUnitService.getAccommodationUnitsResponse1 getAccommodationUnits(AgentApplication.AccommodationUnitService.getAccommodationUnitsRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<AgentApplication.AccommodationUnitService.getAccommodationUnitsResponse1> getAccommodationUnitsAsync(AgentApplication.AccommodationUnitService.getAccommodationUnitsRequest1 request);
        
        // CODEGEN: Generating message contract since the operation getAccommodationUnit is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AgentApplication.AccommodationUnitService.getAccommodationUnitResponse1 getAccommodationUnit(AgentApplication.AccommodationUnitService.getAccommodationUnitRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<AgentApplication.AccommodationUnitService.getAccommodationUnitResponse1> getAccommodationUnitAsync(AgentApplication.AccommodationUnitService.getAccommodationUnitRequest1 request);
        
        // CODEGEN: Generating message contract since the operation updateAccommodationUnit is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void updateAccommodationUnit(AgentApplication.AccommodationUnitService.updateAccommodationUnitRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="")]
        System.Threading.Tasks.Task updateAccommodationUnitAsync(AgentApplication.AccommodationUnitService.updateAccommodationUnitRequest1 request);
        
        // CODEGEN: Generating message contract since the operation addAccommodationUnit is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AgentApplication.AccommodationUnitService.addAccommodationUnitResponse1 addAccommodationUnit(AgentApplication.AccommodationUnitService.addAccommodationUnitRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<AgentApplication.AccommodationUnitService.addAccommodationUnitResponse1> addAccommodationUnitAsync(AgentApplication.AccommodationUnitService.addAccommodationUnitRequest1 request);
        
        // CODEGEN: Generating message contract since the operation removeAccommodationUnit is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void removeAccommodationUnit(AgentApplication.AccommodationUnitService.removeAccommodationUnitRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="")]
        System.Threading.Tasks.Task removeAccommodationUnitAsync(AgentApplication.AccommodationUnitService.removeAccommodationUnitRequest1 request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.projectXml.com/accommodationUnit")]
    public partial class getAccommodationUnitsRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.projectXml.com/accommodationUnit")]
    public partial class Address : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string countryField;
        
        private string cityField;
        
        private int postal_codeField;
        
        private string streetField;
        
        private string numberField;
        
        private string apartment_numberField;
        
        private double longitudeField;
        
        private double latitudeField;
        
        private long idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
                this.RaisePropertyChanged("Country");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
                this.RaisePropertyChanged("City");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int Postal_code {
            get {
                return this.postal_codeField;
            }
            set {
                this.postal_codeField = value;
                this.RaisePropertyChanged("Postal_code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Street {
            get {
                return this.streetField;
            }
            set {
                this.streetField = value;
                this.RaisePropertyChanged("Street");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Number {
            get {
                return this.numberField;
            }
            set {
                this.numberField = value;
                this.RaisePropertyChanged("Number");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Apartment_number {
            get {
                return this.apartment_numberField;
            }
            set {
                this.apartment_numberField = value;
                this.RaisePropertyChanged("Apartment_number");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public double Longitude {
            get {
                return this.longitudeField;
            }
            set {
                this.longitudeField = value;
                this.RaisePropertyChanged("Longitude");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public double Latitude {
            get {
                return this.latitudeField;
            }
            set {
                this.latitudeField = value;
                this.RaisePropertyChanged("Latitude");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public long Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.projectXml.com/accommodationUnit")]
    public partial class accommodation : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string descriptionField;
        
        private string nameField;
        
        private string categoryField;
        
        private Address addressField;
        
        private accommodationType accommodationTypeField;
        
        private long idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("Description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Category {
            get {
                return this.categoryField;
            }
            set {
                this.categoryField = value;
                this.RaisePropertyChanged("Category");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public Address Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
                this.RaisePropertyChanged("Address");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public accommodationType AccommodationType {
            get {
                return this.accommodationTypeField;
            }
            set {
                this.accommodationTypeField = value;
                this.RaisePropertyChanged("AccommodationType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public long Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.projectXml.com/accommodationUnit")]
    public enum accommodationType {
        
        /// <remarks/>
        HOTEL,
        
        /// <remarks/>
        MOTEL,
        
        /// <remarks/>
        BED_AND_BREAKFAST,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.projectXml.com/accommodationUnit")]
    public partial class accommodationUnitType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long idField;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.projectXml.com/accommodationUnit")]
    public partial class accommodationUnit : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int floorField;
        
        private string numberField;
        
        private int numberOfBedsField;
        
        private double defaultPriceField;
        
        private accommodationUnitType accommodationUnitTypeField;
        
        private long idField;
        
        private accommodation accommodationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Floor {
            get {
                return this.floorField;
            }
            set {
                this.floorField = value;
                this.RaisePropertyChanged("Floor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Number {
            get {
                return this.numberField;
            }
            set {
                this.numberField = value;
                this.RaisePropertyChanged("Number");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int NumberOfBeds {
            get {
                return this.numberOfBedsField;
            }
            set {
                this.numberOfBedsField = value;
                this.RaisePropertyChanged("NumberOfBeds");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public double DefaultPrice {
            get {
                return this.defaultPriceField;
            }
            set {
                this.defaultPriceField = value;
                this.RaisePropertyChanged("DefaultPrice");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public accommodationUnitType AccommodationUnitType {
            get {
                return this.accommodationUnitTypeField;
            }
            set {
                this.accommodationUnitTypeField = value;
                this.RaisePropertyChanged("AccommodationUnitType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public long Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public accommodation Accommodation {
            get {
                return this.accommodationField;
            }
            set {
                this.accommodationField = value;
                this.RaisePropertyChanged("Accommodation");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.projectXml.com/accommodationUnit")]
    public partial class getAccommodationUnitsResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private accommodationUnit[] accommodationUnitsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("AccommodationUnits", IsNullable=false)]
        public accommodationUnit[] accommodationUnits {
            get {
                return this.accommodationUnitsField;
            }
            set {
                this.accommodationUnitsField = value;
                this.RaisePropertyChanged("accommodationUnits");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getAccommodationUnitsRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.projectXml.com/accommodationUnit", Order=0)]
        public AgentApplication.AccommodationUnitService.getAccommodationUnitsRequest getAccommodationUnitsRequest;
        
        public getAccommodationUnitsRequest1() {
        }
        
        public getAccommodationUnitsRequest1(AgentApplication.AccommodationUnitService.getAccommodationUnitsRequest getAccommodationUnitsRequest) {
            this.getAccommodationUnitsRequest = getAccommodationUnitsRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getAccommodationUnitsResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.projectXml.com/accommodationUnit", Order=0)]
        public AgentApplication.AccommodationUnitService.getAccommodationUnitsResponse getAccommodationUnitsResponse;
        
        public getAccommodationUnitsResponse1() {
        }
        
        public getAccommodationUnitsResponse1(AgentApplication.AccommodationUnitService.getAccommodationUnitsResponse getAccommodationUnitsResponse) {
            this.getAccommodationUnitsResponse = getAccommodationUnitsResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.projectXml.com/accommodationUnit")]
    public partial class getAccommodationUnitRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long accommodationUnitIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long accommodationUnitId {
            get {
                return this.accommodationUnitIdField;
            }
            set {
                this.accommodationUnitIdField = value;
                this.RaisePropertyChanged("accommodationUnitId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.projectXml.com/accommodationUnit")]
    public partial class getAccommodationUnitResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private accommodationUnit accommodationUnitField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public accommodationUnit accommodationUnit {
            get {
                return this.accommodationUnitField;
            }
            set {
                this.accommodationUnitField = value;
                this.RaisePropertyChanged("accommodationUnit");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getAccommodationUnitRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.projectXml.com/accommodationUnit", Order=0)]
        public AgentApplication.AccommodationUnitService.getAccommodationUnitRequest getAccommodationUnitRequest;
        
        public getAccommodationUnitRequest1() {
        }
        
        public getAccommodationUnitRequest1(AgentApplication.AccommodationUnitService.getAccommodationUnitRequest getAccommodationUnitRequest) {
            this.getAccommodationUnitRequest = getAccommodationUnitRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getAccommodationUnitResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.projectXml.com/accommodationUnit", Order=0)]
        public AgentApplication.AccommodationUnitService.getAccommodationUnitResponse getAccommodationUnitResponse;
        
        public getAccommodationUnitResponse1() {
        }
        
        public getAccommodationUnitResponse1(AgentApplication.AccommodationUnitService.getAccommodationUnitResponse getAccommodationUnitResponse) {
            this.getAccommodationUnitResponse = getAccommodationUnitResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.projectXml.com/accommodationUnit")]
    public partial class updateAccommodationUnitRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private accommodationUnit accommodationUnitField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public accommodationUnit accommodationUnit {
            get {
                return this.accommodationUnitField;
            }
            set {
                this.accommodationUnitField = value;
                this.RaisePropertyChanged("accommodationUnit");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class updateAccommodationUnitRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.projectXml.com/accommodationUnit", Order=0)]
        public AgentApplication.AccommodationUnitService.updateAccommodationUnitRequest updateAccommodationUnitRequest;
        
        public updateAccommodationUnitRequest1() {
        }
        
        public updateAccommodationUnitRequest1(AgentApplication.AccommodationUnitService.updateAccommodationUnitRequest updateAccommodationUnitRequest) {
            this.updateAccommodationUnitRequest = updateAccommodationUnitRequest;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.projectXml.com/accommodationUnit")]
    public partial class addAccommodationUnitRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long accommodationIdField;
        
        private accommodationUnit accommodationUnitField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long accommodationId {
            get {
                return this.accommodationIdField;
            }
            set {
                this.accommodationIdField = value;
                this.RaisePropertyChanged("accommodationId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public accommodationUnit accommodationUnit {
            get {
                return this.accommodationUnitField;
            }
            set {
                this.accommodationUnitField = value;
                this.RaisePropertyChanged("accommodationUnit");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.projectXml.com/accommodationUnit")]
    public partial class addAccommodationUnitResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private accommodationUnit accommodationUnitField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public accommodationUnit accommodationUnit {
            get {
                return this.accommodationUnitField;
            }
            set {
                this.accommodationUnitField = value;
                this.RaisePropertyChanged("accommodationUnit");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class addAccommodationUnitRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.projectXml.com/accommodationUnit", Order=0)]
        public AgentApplication.AccommodationUnitService.addAccommodationUnitRequest addAccommodationUnitRequest;
        
        public addAccommodationUnitRequest1() {
        }
        
        public addAccommodationUnitRequest1(AgentApplication.AccommodationUnitService.addAccommodationUnitRequest addAccommodationUnitRequest) {
            this.addAccommodationUnitRequest = addAccommodationUnitRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class addAccommodationUnitResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.projectXml.com/accommodationUnit", Order=0)]
        public AgentApplication.AccommodationUnitService.addAccommodationUnitResponse addAccommodationUnitResponse;
        
        public addAccommodationUnitResponse1() {
        }
        
        public addAccommodationUnitResponse1(AgentApplication.AccommodationUnitService.addAccommodationUnitResponse addAccommodationUnitResponse) {
            this.addAccommodationUnitResponse = addAccommodationUnitResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.projectXml.com/accommodationUnit")]
    public partial class removeAccommodationUnitRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long accommodationUnitIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long accommodationUnitId {
            get {
                return this.accommodationUnitIdField;
            }
            set {
                this.accommodationUnitIdField = value;
                this.RaisePropertyChanged("accommodationUnitId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class removeAccommodationUnitRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.projectXml.com/accommodationUnit", Order=0)]
        public AgentApplication.AccommodationUnitService.removeAccommodationUnitRequest removeAccommodationUnitRequest;
        
        public removeAccommodationUnitRequest1() {
        }
        
        public removeAccommodationUnitRequest1(AgentApplication.AccommodationUnitService.removeAccommodationUnitRequest removeAccommodationUnitRequest) {
            this.removeAccommodationUnitRequest = removeAccommodationUnitRequest;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AccommodationUnitPortChannel : AgentApplication.AccommodationUnitService.AccommodationUnitPort, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AccommodationUnitPortClient : System.ServiceModel.ClientBase<AgentApplication.AccommodationUnitService.AccommodationUnitPort>, AgentApplication.AccommodationUnitService.AccommodationUnitPort {
        
        public AccommodationUnitPortClient() {
        }
        
        public AccommodationUnitPortClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AccommodationUnitPortClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AccommodationUnitPortClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AccommodationUnitPortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AgentApplication.AccommodationUnitService.getAccommodationUnitsResponse1 AgentApplication.AccommodationUnitService.AccommodationUnitPort.getAccommodationUnits(AgentApplication.AccommodationUnitService.getAccommodationUnitsRequest1 request) {
            return base.Channel.getAccommodationUnits(request);
        }
        
        public AgentApplication.AccommodationUnitService.getAccommodationUnitsResponse getAccommodationUnits(AgentApplication.AccommodationUnitService.getAccommodationUnitsRequest getAccommodationUnitsRequest) {
            AgentApplication.AccommodationUnitService.getAccommodationUnitsRequest1 inValue = new AgentApplication.AccommodationUnitService.getAccommodationUnitsRequest1();
            inValue.getAccommodationUnitsRequest = getAccommodationUnitsRequest;
            AgentApplication.AccommodationUnitService.getAccommodationUnitsResponse1 retVal = ((AgentApplication.AccommodationUnitService.AccommodationUnitPort)(this)).getAccommodationUnits(inValue);
            return retVal.getAccommodationUnitsResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AgentApplication.AccommodationUnitService.getAccommodationUnitsResponse1> AgentApplication.AccommodationUnitService.AccommodationUnitPort.getAccommodationUnitsAsync(AgentApplication.AccommodationUnitService.getAccommodationUnitsRequest1 request) {
            return base.Channel.getAccommodationUnitsAsync(request);
        }
        
        public System.Threading.Tasks.Task<AgentApplication.AccommodationUnitService.getAccommodationUnitsResponse1> getAccommodationUnitsAsync(AgentApplication.AccommodationUnitService.getAccommodationUnitsRequest getAccommodationUnitsRequest) {
            AgentApplication.AccommodationUnitService.getAccommodationUnitsRequest1 inValue = new AgentApplication.AccommodationUnitService.getAccommodationUnitsRequest1();
            inValue.getAccommodationUnitsRequest = getAccommodationUnitsRequest;
            return ((AgentApplication.AccommodationUnitService.AccommodationUnitPort)(this)).getAccommodationUnitsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AgentApplication.AccommodationUnitService.getAccommodationUnitResponse1 AgentApplication.AccommodationUnitService.AccommodationUnitPort.getAccommodationUnit(AgentApplication.AccommodationUnitService.getAccommodationUnitRequest1 request) {
            return base.Channel.getAccommodationUnit(request);
        }
        
        public AgentApplication.AccommodationUnitService.getAccommodationUnitResponse getAccommodationUnit(AgentApplication.AccommodationUnitService.getAccommodationUnitRequest getAccommodationUnitRequest) {
            AgentApplication.AccommodationUnitService.getAccommodationUnitRequest1 inValue = new AgentApplication.AccommodationUnitService.getAccommodationUnitRequest1();
            inValue.getAccommodationUnitRequest = getAccommodationUnitRequest;
            AgentApplication.AccommodationUnitService.getAccommodationUnitResponse1 retVal = ((AgentApplication.AccommodationUnitService.AccommodationUnitPort)(this)).getAccommodationUnit(inValue);
            return retVal.getAccommodationUnitResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AgentApplication.AccommodationUnitService.getAccommodationUnitResponse1> AgentApplication.AccommodationUnitService.AccommodationUnitPort.getAccommodationUnitAsync(AgentApplication.AccommodationUnitService.getAccommodationUnitRequest1 request) {
            return base.Channel.getAccommodationUnitAsync(request);
        }
        
        public System.Threading.Tasks.Task<AgentApplication.AccommodationUnitService.getAccommodationUnitResponse1> getAccommodationUnitAsync(AgentApplication.AccommodationUnitService.getAccommodationUnitRequest getAccommodationUnitRequest) {
            AgentApplication.AccommodationUnitService.getAccommodationUnitRequest1 inValue = new AgentApplication.AccommodationUnitService.getAccommodationUnitRequest1();
            inValue.getAccommodationUnitRequest = getAccommodationUnitRequest;
            return ((AgentApplication.AccommodationUnitService.AccommodationUnitPort)(this)).getAccommodationUnitAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void AgentApplication.AccommodationUnitService.AccommodationUnitPort.updateAccommodationUnit(AgentApplication.AccommodationUnitService.updateAccommodationUnitRequest1 request) {
            base.Channel.updateAccommodationUnit(request);
        }
        
        public void updateAccommodationUnit(AgentApplication.AccommodationUnitService.updateAccommodationUnitRequest updateAccommodationUnitRequest) {
            AgentApplication.AccommodationUnitService.updateAccommodationUnitRequest1 inValue = new AgentApplication.AccommodationUnitService.updateAccommodationUnitRequest1();
            inValue.updateAccommodationUnitRequest = updateAccommodationUnitRequest;
            ((AgentApplication.AccommodationUnitService.AccommodationUnitPort)(this)).updateAccommodationUnit(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task AgentApplication.AccommodationUnitService.AccommodationUnitPort.updateAccommodationUnitAsync(AgentApplication.AccommodationUnitService.updateAccommodationUnitRequest1 request) {
            return base.Channel.updateAccommodationUnitAsync(request);
        }
        
        public System.Threading.Tasks.Task updateAccommodationUnitAsync(AgentApplication.AccommodationUnitService.updateAccommodationUnitRequest updateAccommodationUnitRequest) {
            AgentApplication.AccommodationUnitService.updateAccommodationUnitRequest1 inValue = new AgentApplication.AccommodationUnitService.updateAccommodationUnitRequest1();
            inValue.updateAccommodationUnitRequest = updateAccommodationUnitRequest;
            return ((AgentApplication.AccommodationUnitService.AccommodationUnitPort)(this)).updateAccommodationUnitAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AgentApplication.AccommodationUnitService.addAccommodationUnitResponse1 AgentApplication.AccommodationUnitService.AccommodationUnitPort.addAccommodationUnit(AgentApplication.AccommodationUnitService.addAccommodationUnitRequest1 request) {
            return base.Channel.addAccommodationUnit(request);
        }
        
        public AgentApplication.AccommodationUnitService.addAccommodationUnitResponse addAccommodationUnit(AgentApplication.AccommodationUnitService.addAccommodationUnitRequest addAccommodationUnitRequest) {
            AgentApplication.AccommodationUnitService.addAccommodationUnitRequest1 inValue = new AgentApplication.AccommodationUnitService.addAccommodationUnitRequest1();
            inValue.addAccommodationUnitRequest = addAccommodationUnitRequest;
            AgentApplication.AccommodationUnitService.addAccommodationUnitResponse1 retVal = ((AgentApplication.AccommodationUnitService.AccommodationUnitPort)(this)).addAccommodationUnit(inValue);
            return retVal.addAccommodationUnitResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AgentApplication.AccommodationUnitService.addAccommodationUnitResponse1> AgentApplication.AccommodationUnitService.AccommodationUnitPort.addAccommodationUnitAsync(AgentApplication.AccommodationUnitService.addAccommodationUnitRequest1 request) {
            return base.Channel.addAccommodationUnitAsync(request);
        }
        
        public System.Threading.Tasks.Task<AgentApplication.AccommodationUnitService.addAccommodationUnitResponse1> addAccommodationUnitAsync(AgentApplication.AccommodationUnitService.addAccommodationUnitRequest addAccommodationUnitRequest) {
            AgentApplication.AccommodationUnitService.addAccommodationUnitRequest1 inValue = new AgentApplication.AccommodationUnitService.addAccommodationUnitRequest1();
            inValue.addAccommodationUnitRequest = addAccommodationUnitRequest;
            return ((AgentApplication.AccommodationUnitService.AccommodationUnitPort)(this)).addAccommodationUnitAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void AgentApplication.AccommodationUnitService.AccommodationUnitPort.removeAccommodationUnit(AgentApplication.AccommodationUnitService.removeAccommodationUnitRequest1 request) {
            base.Channel.removeAccommodationUnit(request);
        }
        
        public void removeAccommodationUnit(AgentApplication.AccommodationUnitService.removeAccommodationUnitRequest removeAccommodationUnitRequest) {
            AgentApplication.AccommodationUnitService.removeAccommodationUnitRequest1 inValue = new AgentApplication.AccommodationUnitService.removeAccommodationUnitRequest1();
            inValue.removeAccommodationUnitRequest = removeAccommodationUnitRequest;
            ((AgentApplication.AccommodationUnitService.AccommodationUnitPort)(this)).removeAccommodationUnit(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task AgentApplication.AccommodationUnitService.AccommodationUnitPort.removeAccommodationUnitAsync(AgentApplication.AccommodationUnitService.removeAccommodationUnitRequest1 request) {
            return base.Channel.removeAccommodationUnitAsync(request);
        }
        
        public System.Threading.Tasks.Task removeAccommodationUnitAsync(AgentApplication.AccommodationUnitService.removeAccommodationUnitRequest removeAccommodationUnitRequest) {
            AgentApplication.AccommodationUnitService.removeAccommodationUnitRequest1 inValue = new AgentApplication.AccommodationUnitService.removeAccommodationUnitRequest1();
            inValue.removeAccommodationUnitRequest = removeAccommodationUnitRequest;
            return ((AgentApplication.AccommodationUnitService.AccommodationUnitPort)(this)).removeAccommodationUnitAsync(inValue);
        }
    }
}
