//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using AgentApplication.Model;
using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://booking.uns.ac.rs/reservation")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://booking.uns.ac.rs/reservation", IsNullable=false)]
public partial class Reservation {
    
    private System.DateTime from_dateField;
    
    private System.DateTime to_dateField;
    
    private bool confirmedField;
    
    private ReservationConversation conversationField;
    
    private ReservationComment_rate comment_rateField;
    
    private AccommodationUnit accommodation_unitField;
    
    private User guestField;
    
    private long idField;
    
    /// <remarks/>
    public System.DateTime From_date {
        get {
            return this.from_dateField;
        }
        set {
            this.from_dateField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime To_date {
        get {
            return this.to_dateField;
        }
        set {
            this.to_dateField = value;
        }
    }
    
    /// <remarks/>
    public bool Confirmed {
        get {
            return this.confirmedField;
        }
        set {
            this.confirmedField = value;
        }
    }
    
    /// <remarks/>
    public ReservationConversation conversation {
        get {
            return this.conversationField;
        }
        set {
            this.conversationField = value;
        }
    }
    
    /// <remarks/>
    public ReservationComment_rate Comment_rate {
        get {
            return this.comment_rateField;
        }
        set {
            this.comment_rateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Namespace="http://booking.uns.ac.rs/accommodation")]
    public AccommodationUnit Accommodation_unit {
        get {
            return this.accommodation_unitField;
        }
        set {
            this.accommodation_unitField = value;
        }
    }
    
    /// <remarks/>
    public User Guest {
        get {
            return this.guestField;
        }
        set {
            this.guestField = value;
        }
    }
    
    /// <remarks/>
    public long Id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://booking.uns.ac.rs/reservation")]
public partial class ReservationConversation {
    
    private Message messageField;
    
    /// <remarks/>
    public Message Message {
        get {
            return this.messageField;
        }
        set {
            this.messageField = value;
        }
    }
}


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://booking.uns.ac.rs/reservation")]
public partial class ReservationComment_rate {
    
    private ReservationComment_rateKomentar komentarField;
    
    private int ocenaField;
    
    private System.DateTime datum_vremeField;
    
    private bool datum_vremeFieldSpecified;
    
    /// <remarks/>
    public ReservationComment_rateKomentar Komentar {
        get {
            return this.komentarField;
        }
        set {
            this.komentarField = value;
        }
    }
    
    /// <remarks/>
    public int Ocena {
        get {
            return this.ocenaField;
        }
        set {
            this.ocenaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public System.DateTime Datum_vreme {
        get {
            return this.datum_vremeField;
        }
        set {
            this.datum_vremeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool Datum_vremeSpecified {
        get {
            return this.datum_vremeFieldSpecified;
        }
        set {
            this.datum_vremeFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://booking.uns.ac.rs/reservation")]
public partial class ReservationComment_rateKomentar {
    
    private bool odobrenField;
    
    private bool odobrenFieldSpecified;
    
    private string sadrzajField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool Odobren {
        get {
            return this.odobrenField;
        }
        set {
            this.odobrenField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool OdobrenSpecified {
        get {
            return this.odobrenFieldSpecified;
        }
        set {
            this.odobrenFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Sadrzaj {
        get {
            return this.sadrzajField;
        }
        set {
            this.sadrzajField = value;
        }
    }
}





/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://booking.uns.ac.rs/accommodation")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://booking.uns.ac.rs/accommodation", IsNullable=false)]
public partial class Accommodation_type {
    
    private string nameField;
    
    private long idField;
    
    /// <remarks/>
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    public long Id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
}
