//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgentApplication.PeriodPriceService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.projectXml.com/periodPrices", ConfigurationName="PeriodPriceService.PeriodPricePort")]
    public interface PeriodPricePort {
        
        // CODEGEN: Generating message contract since the operation removePeriodPrice is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void removePeriodPrice(AgentApplication.PeriodPriceService.removePeriodPriceRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="")]
        System.Threading.Tasks.Task removePeriodPriceAsync(AgentApplication.PeriodPriceService.removePeriodPriceRequest1 request);
        
        // CODEGEN: Generating message contract since the operation getPeriodPriceForMonth is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AgentApplication.PeriodPriceService.getPeriodPriceForMonthResponse1 getPeriodPriceForMonth(AgentApplication.PeriodPriceService.getPeriodPriceForMonthRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<AgentApplication.PeriodPriceService.getPeriodPriceForMonthResponse1> getPeriodPriceForMonthAsync(AgentApplication.PeriodPriceService.getPeriodPriceForMonthRequest1 request);
        
        // CODEGEN: Generating message contract since the operation updatePeriodPrice is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void updatePeriodPrice(AgentApplication.PeriodPriceService.updatePeriodPriceRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="")]
        System.Threading.Tasks.Task updatePeriodPriceAsync(AgentApplication.PeriodPriceService.updatePeriodPriceRequest1 request);
        
        // CODEGEN: Generating message contract since the operation getPeriodPrice is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AgentApplication.PeriodPriceService.getPeriodPriceResponse1 getPeriodPrice(AgentApplication.PeriodPriceService.getPeriodPriceRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<AgentApplication.PeriodPriceService.getPeriodPriceResponse1> getPeriodPriceAsync(AgentApplication.PeriodPriceService.getPeriodPriceRequest1 request);
        
        // CODEGEN: Generating message contract since the operation getPeriodPrices is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AgentApplication.PeriodPriceService.getPeriodPricesResponse1 getPeriodPrices(AgentApplication.PeriodPriceService.getPeriodPricesRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<AgentApplication.PeriodPriceService.getPeriodPricesResponse1> getPeriodPricesAsync(AgentApplication.PeriodPriceService.getPeriodPricesRequest1 request);
        
        // CODEGEN: Generating message contract since the operation addPeriodPrice is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AgentApplication.PeriodPriceService.addPeriodPriceResponse1 addPeriodPrice(AgentApplication.PeriodPriceService.addPeriodPriceRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<AgentApplication.PeriodPriceService.addPeriodPriceResponse1> addPeriodPriceAsync(AgentApplication.PeriodPriceService.addPeriodPriceRequest1 request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.projectXml.com/periodPrice")]
    public partial class removePeriodPriceRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long periodPriceIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long periodPriceId {
            get {
                return this.periodPriceIdField;
            }
            set {
                this.periodPriceIdField = value;
                this.RaisePropertyChanged("periodPriceId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.projectXml.com/periodPrice")]
    public partial class Address : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string countryField;
        
        private string cityField;
        
        private int postal_codeField;
        
        private string streetField;
        
        private string numberField;
        
        private string apartment_numberField;
        
        private double longitudeField;
        
        private double latitudeField;
        
        private long idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
                this.RaisePropertyChanged("Country");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
                this.RaisePropertyChanged("City");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int Postal_code {
            get {
                return this.postal_codeField;
            }
            set {
                this.postal_codeField = value;
                this.RaisePropertyChanged("Postal_code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Street {
            get {
                return this.streetField;
            }
            set {
                this.streetField = value;
                this.RaisePropertyChanged("Street");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Number {
            get {
                return this.numberField;
            }
            set {
                this.numberField = value;
                this.RaisePropertyChanged("Number");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Apartment_number {
            get {
                return this.apartment_numberField;
            }
            set {
                this.apartment_numberField = value;
                this.RaisePropertyChanged("Apartment_number");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public double Longitude {
            get {
                return this.longitudeField;
            }
            set {
                this.longitudeField = value;
                this.RaisePropertyChanged("Longitude");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public double Latitude {
            get {
                return this.latitudeField;
            }
            set {
                this.latitudeField = value;
                this.RaisePropertyChanged("Latitude");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public long Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.projectXml.com/periodPrice")]
    public partial class accommodation : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string descriptionField;
        
        private string nameField;
        
        private string categoryField;
        
        private Address addressField;
        
        private accommodationType accommodationTypeField;
        
        private long idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("Description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Category {
            get {
                return this.categoryField;
            }
            set {
                this.categoryField = value;
                this.RaisePropertyChanged("Category");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public Address Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
                this.RaisePropertyChanged("Address");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public accommodationType AccommodationType {
            get {
                return this.accommodationTypeField;
            }
            set {
                this.accommodationTypeField = value;
                this.RaisePropertyChanged("AccommodationType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public long Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.projectXml.com/periodPrice")]
    public enum accommodationType {
        
        /// <remarks/>
        HOTEL,
        
        /// <remarks/>
        MOTEL,
        
        /// <remarks/>
        BED_AND_BREAKFAST,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.projectXml.com/periodPrice")]
    public partial class accommodationUnitType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long idField;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.projectXml.com/periodPrice")]
    public partial class accommodationUnit : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int floorField;
        
        private string numberField;
        
        private int numberOfBedsField;
        
        private double defaultPriceField;
        
        private accommodationUnitType accommodationUnitTypeField;
        
        private long idField;
        
        private accommodation accommodationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Floor {
            get {
                return this.floorField;
            }
            set {
                this.floorField = value;
                this.RaisePropertyChanged("Floor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Number {
            get {
                return this.numberField;
            }
            set {
                this.numberField = value;
                this.RaisePropertyChanged("Number");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int NumberOfBeds {
            get {
                return this.numberOfBedsField;
            }
            set {
                this.numberOfBedsField = value;
                this.RaisePropertyChanged("NumberOfBeds");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public double DefaultPrice {
            get {
                return this.defaultPriceField;
            }
            set {
                this.defaultPriceField = value;
                this.RaisePropertyChanged("DefaultPrice");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public accommodationUnitType AccommodationUnitType {
            get {
                return this.accommodationUnitTypeField;
            }
            set {
                this.accommodationUnitTypeField = value;
                this.RaisePropertyChanged("AccommodationUnitType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public long Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public accommodation Accommodation {
            get {
                return this.accommodationField;
            }
            set {
                this.accommodationField = value;
                this.RaisePropertyChanged("Accommodation");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.projectXml.com/periodPrice")]
    public partial class periodPrice : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long idField;
        
        private double priceField;
        
        private accommodationUnit accommodationUnitField;
        
        private System.DateTime fromDateField;
        
        private System.DateTime toDateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public double Price {
            get {
                return this.priceField;
            }
            set {
                this.priceField = value;
                this.RaisePropertyChanged("Price");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public accommodationUnit AccommodationUnit {
            get {
                return this.accommodationUnitField;
            }
            set {
                this.accommodationUnitField = value;
                this.RaisePropertyChanged("AccommodationUnit");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=3)]
        public System.DateTime FromDate {
            get {
                return this.fromDateField;
            }
            set {
                this.fromDateField = value;
                this.RaisePropertyChanged("FromDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=4)]
        public System.DateTime ToDate {
            get {
                return this.toDateField;
            }
            set {
                this.toDateField = value;
                this.RaisePropertyChanged("ToDate");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.projectXml.com/periodPrice")]
    public partial class periodPriceDates : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.DateTime fromDateField;
        
        private System.DateTime toDateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=0)]
        public System.DateTime FromDate {
            get {
                return this.fromDateField;
            }
            set {
                this.fromDateField = value;
                this.RaisePropertyChanged("FromDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=1)]
        public System.DateTime ToDate {
            get {
                return this.toDateField;
            }
            set {
                this.toDateField = value;
                this.RaisePropertyChanged("ToDate");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class removePeriodPriceRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.projectXml.com/periodPrice", Order=0)]
        public AgentApplication.PeriodPriceService.removePeriodPriceRequest removePeriodPriceRequest;
        
        public removePeriodPriceRequest1() {
        }
        
        public removePeriodPriceRequest1(AgentApplication.PeriodPriceService.removePeriodPriceRequest removePeriodPriceRequest) {
            this.removePeriodPriceRequest = removePeriodPriceRequest;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.projectXml.com/periodPrice")]
    public partial class getPeriodPriceForMonthRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long accommodationUnitIdField;
        
        private periodPriceDates periodPriceDatesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long accommodationUnitId {
            get {
                return this.accommodationUnitIdField;
            }
            set {
                this.accommodationUnitIdField = value;
                this.RaisePropertyChanged("accommodationUnitId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public periodPriceDates periodPriceDates {
            get {
                return this.periodPriceDatesField;
            }
            set {
                this.periodPriceDatesField = value;
                this.RaisePropertyChanged("periodPriceDates");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.projectXml.com/periodPrice")]
    public partial class getPeriodPriceForMonthResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private periodPrice periodPriceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public periodPrice periodPrice {
            get {
                return this.periodPriceField;
            }
            set {
                this.periodPriceField = value;
                this.RaisePropertyChanged("periodPrice");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getPeriodPriceForMonthRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.projectXml.com/periodPrice", Order=0)]
        public AgentApplication.PeriodPriceService.getPeriodPriceForMonthRequest getPeriodPriceForMonthRequest;
        
        public getPeriodPriceForMonthRequest1() {
        }
        
        public getPeriodPriceForMonthRequest1(AgentApplication.PeriodPriceService.getPeriodPriceForMonthRequest getPeriodPriceForMonthRequest) {
            this.getPeriodPriceForMonthRequest = getPeriodPriceForMonthRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getPeriodPriceForMonthResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.projectXml.com/periodPrice", Order=0)]
        public AgentApplication.PeriodPriceService.getPeriodPriceForMonthResponse getPeriodPriceForMonthResponse;
        
        public getPeriodPriceForMonthResponse1() {
        }
        
        public getPeriodPriceForMonthResponse1(AgentApplication.PeriodPriceService.getPeriodPriceForMonthResponse getPeriodPriceForMonthResponse) {
            this.getPeriodPriceForMonthResponse = getPeriodPriceForMonthResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.projectXml.com/periodPrice")]
    public partial class updatePeriodPriceRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private periodPrice periodPriceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public periodPrice periodPrice {
            get {
                return this.periodPriceField;
            }
            set {
                this.periodPriceField = value;
                this.RaisePropertyChanged("periodPrice");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class updatePeriodPriceRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.projectXml.com/periodPrice", Order=0)]
        public AgentApplication.PeriodPriceService.updatePeriodPriceRequest updatePeriodPriceRequest;
        
        public updatePeriodPriceRequest1() {
        }
        
        public updatePeriodPriceRequest1(AgentApplication.PeriodPriceService.updatePeriodPriceRequest updatePeriodPriceRequest) {
            this.updatePeriodPriceRequest = updatePeriodPriceRequest;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.projectXml.com/periodPrice")]
    public partial class getPeriodPriceRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long periodPriceIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long periodPriceId {
            get {
                return this.periodPriceIdField;
            }
            set {
                this.periodPriceIdField = value;
                this.RaisePropertyChanged("periodPriceId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.projectXml.com/periodPrice")]
    public partial class getPeriodPriceResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private periodPrice periodPriceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public periodPrice periodPrice {
            get {
                return this.periodPriceField;
            }
            set {
                this.periodPriceField = value;
                this.RaisePropertyChanged("periodPrice");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getPeriodPriceRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.projectXml.com/periodPrice", Order=0)]
        public AgentApplication.PeriodPriceService.getPeriodPriceRequest getPeriodPriceRequest;
        
        public getPeriodPriceRequest1() {
        }
        
        public getPeriodPriceRequest1(AgentApplication.PeriodPriceService.getPeriodPriceRequest getPeriodPriceRequest) {
            this.getPeriodPriceRequest = getPeriodPriceRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getPeriodPriceResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.projectXml.com/periodPrice", Order=0)]
        public AgentApplication.PeriodPriceService.getPeriodPriceResponse getPeriodPriceResponse;
        
        public getPeriodPriceResponse1() {
        }
        
        public getPeriodPriceResponse1(AgentApplication.PeriodPriceService.getPeriodPriceResponse getPeriodPriceResponse) {
            this.getPeriodPriceResponse = getPeriodPriceResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.projectXml.com/periodPrice")]
    public partial class getPeriodPricesRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long accommodationUnitIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long accommodationUnitId {
            get {
                return this.accommodationUnitIdField;
            }
            set {
                this.accommodationUnitIdField = value;
                this.RaisePropertyChanged("accommodationUnitId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.projectXml.com/periodPrice")]
    public partial class getPeriodPricesResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private periodPrice[] periodPricesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("PeriodPrice", IsNullable=false)]
        public periodPrice[] periodPrices {
            get {
                return this.periodPricesField;
            }
            set {
                this.periodPricesField = value;
                this.RaisePropertyChanged("periodPrices");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getPeriodPricesRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.projectXml.com/periodPrice", Order=0)]
        public AgentApplication.PeriodPriceService.getPeriodPricesRequest getPeriodPricesRequest;
        
        public getPeriodPricesRequest1() {
        }
        
        public getPeriodPricesRequest1(AgentApplication.PeriodPriceService.getPeriodPricesRequest getPeriodPricesRequest) {
            this.getPeriodPricesRequest = getPeriodPricesRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getPeriodPricesResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.projectXml.com/periodPrice", Order=0)]
        public AgentApplication.PeriodPriceService.getPeriodPricesResponse getPeriodPricesResponse;
        
        public getPeriodPricesResponse1() {
        }
        
        public getPeriodPricesResponse1(AgentApplication.PeriodPriceService.getPeriodPricesResponse getPeriodPricesResponse) {
            this.getPeriodPricesResponse = getPeriodPricesResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.projectXml.com/periodPrice")]
    public partial class addPeriodPriceRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long accommodationUnitIdField;
        
        private periodPrice periodPriceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long accommodationUnitId {
            get {
                return this.accommodationUnitIdField;
            }
            set {
                this.accommodationUnitIdField = value;
                this.RaisePropertyChanged("accommodationUnitId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public periodPrice periodPrice {
            get {
                return this.periodPriceField;
            }
            set {
                this.periodPriceField = value;
                this.RaisePropertyChanged("periodPrice");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.projectXml.com/periodPrice")]
    public partial class addPeriodPriceResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private periodPrice periodPriceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public periodPrice periodPrice {
            get {
                return this.periodPriceField;
            }
            set {
                this.periodPriceField = value;
                this.RaisePropertyChanged("periodPrice");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class addPeriodPriceRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.projectXml.com/periodPrice", Order=0)]
        public AgentApplication.PeriodPriceService.addPeriodPriceRequest addPeriodPriceRequest;
        
        public addPeriodPriceRequest1() {
        }
        
        public addPeriodPriceRequest1(AgentApplication.PeriodPriceService.addPeriodPriceRequest addPeriodPriceRequest) {
            this.addPeriodPriceRequest = addPeriodPriceRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class addPeriodPriceResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.projectXml.com/periodPrice", Order=0)]
        public AgentApplication.PeriodPriceService.addPeriodPriceResponse addPeriodPriceResponse;
        
        public addPeriodPriceResponse1() {
        }
        
        public addPeriodPriceResponse1(AgentApplication.PeriodPriceService.addPeriodPriceResponse addPeriodPriceResponse) {
            this.addPeriodPriceResponse = addPeriodPriceResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PeriodPricePortChannel : AgentApplication.PeriodPriceService.PeriodPricePort, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PeriodPricePortClient : System.ServiceModel.ClientBase<AgentApplication.PeriodPriceService.PeriodPricePort>, AgentApplication.PeriodPriceService.PeriodPricePort {
        
        public PeriodPricePortClient() {
        }
        
        public PeriodPricePortClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PeriodPricePortClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PeriodPricePortClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PeriodPricePortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void AgentApplication.PeriodPriceService.PeriodPricePort.removePeriodPrice(AgentApplication.PeriodPriceService.removePeriodPriceRequest1 request) {
            base.Channel.removePeriodPrice(request);
        }
        
        public void removePeriodPrice(AgentApplication.PeriodPriceService.removePeriodPriceRequest removePeriodPriceRequest) {
            AgentApplication.PeriodPriceService.removePeriodPriceRequest1 inValue = new AgentApplication.PeriodPriceService.removePeriodPriceRequest1();
            inValue.removePeriodPriceRequest = removePeriodPriceRequest;
            ((AgentApplication.PeriodPriceService.PeriodPricePort)(this)).removePeriodPrice(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task AgentApplication.PeriodPriceService.PeriodPricePort.removePeriodPriceAsync(AgentApplication.PeriodPriceService.removePeriodPriceRequest1 request) {
            return base.Channel.removePeriodPriceAsync(request);
        }
        
        public System.Threading.Tasks.Task removePeriodPriceAsync(AgentApplication.PeriodPriceService.removePeriodPriceRequest removePeriodPriceRequest) {
            AgentApplication.PeriodPriceService.removePeriodPriceRequest1 inValue = new AgentApplication.PeriodPriceService.removePeriodPriceRequest1();
            inValue.removePeriodPriceRequest = removePeriodPriceRequest;
            return ((AgentApplication.PeriodPriceService.PeriodPricePort)(this)).removePeriodPriceAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AgentApplication.PeriodPriceService.getPeriodPriceForMonthResponse1 AgentApplication.PeriodPriceService.PeriodPricePort.getPeriodPriceForMonth(AgentApplication.PeriodPriceService.getPeriodPriceForMonthRequest1 request) {
            return base.Channel.getPeriodPriceForMonth(request);
        }
        
        public AgentApplication.PeriodPriceService.getPeriodPriceForMonthResponse getPeriodPriceForMonth(AgentApplication.PeriodPriceService.getPeriodPriceForMonthRequest getPeriodPriceForMonthRequest) {
            AgentApplication.PeriodPriceService.getPeriodPriceForMonthRequest1 inValue = new AgentApplication.PeriodPriceService.getPeriodPriceForMonthRequest1();
            inValue.getPeriodPriceForMonthRequest = getPeriodPriceForMonthRequest;
            AgentApplication.PeriodPriceService.getPeriodPriceForMonthResponse1 retVal = ((AgentApplication.PeriodPriceService.PeriodPricePort)(this)).getPeriodPriceForMonth(inValue);
            return retVal.getPeriodPriceForMonthResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AgentApplication.PeriodPriceService.getPeriodPriceForMonthResponse1> AgentApplication.PeriodPriceService.PeriodPricePort.getPeriodPriceForMonthAsync(AgentApplication.PeriodPriceService.getPeriodPriceForMonthRequest1 request) {
            return base.Channel.getPeriodPriceForMonthAsync(request);
        }
        
        public System.Threading.Tasks.Task<AgentApplication.PeriodPriceService.getPeriodPriceForMonthResponse1> getPeriodPriceForMonthAsync(AgentApplication.PeriodPriceService.getPeriodPriceForMonthRequest getPeriodPriceForMonthRequest) {
            AgentApplication.PeriodPriceService.getPeriodPriceForMonthRequest1 inValue = new AgentApplication.PeriodPriceService.getPeriodPriceForMonthRequest1();
            inValue.getPeriodPriceForMonthRequest = getPeriodPriceForMonthRequest;
            return ((AgentApplication.PeriodPriceService.PeriodPricePort)(this)).getPeriodPriceForMonthAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void AgentApplication.PeriodPriceService.PeriodPricePort.updatePeriodPrice(AgentApplication.PeriodPriceService.updatePeriodPriceRequest1 request) {
            base.Channel.updatePeriodPrice(request);
        }
        
        public void updatePeriodPrice(AgentApplication.PeriodPriceService.updatePeriodPriceRequest updatePeriodPriceRequest) {
            AgentApplication.PeriodPriceService.updatePeriodPriceRequest1 inValue = new AgentApplication.PeriodPriceService.updatePeriodPriceRequest1();
            inValue.updatePeriodPriceRequest = updatePeriodPriceRequest;
            ((AgentApplication.PeriodPriceService.PeriodPricePort)(this)).updatePeriodPrice(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task AgentApplication.PeriodPriceService.PeriodPricePort.updatePeriodPriceAsync(AgentApplication.PeriodPriceService.updatePeriodPriceRequest1 request) {
            return base.Channel.updatePeriodPriceAsync(request);
        }
        
        public System.Threading.Tasks.Task updatePeriodPriceAsync(AgentApplication.PeriodPriceService.updatePeriodPriceRequest updatePeriodPriceRequest) {
            AgentApplication.PeriodPriceService.updatePeriodPriceRequest1 inValue = new AgentApplication.PeriodPriceService.updatePeriodPriceRequest1();
            inValue.updatePeriodPriceRequest = updatePeriodPriceRequest;
            return ((AgentApplication.PeriodPriceService.PeriodPricePort)(this)).updatePeriodPriceAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AgentApplication.PeriodPriceService.getPeriodPriceResponse1 AgentApplication.PeriodPriceService.PeriodPricePort.getPeriodPrice(AgentApplication.PeriodPriceService.getPeriodPriceRequest1 request) {
            return base.Channel.getPeriodPrice(request);
        }
        
        public AgentApplication.PeriodPriceService.getPeriodPriceResponse getPeriodPrice(AgentApplication.PeriodPriceService.getPeriodPriceRequest getPeriodPriceRequest) {
            AgentApplication.PeriodPriceService.getPeriodPriceRequest1 inValue = new AgentApplication.PeriodPriceService.getPeriodPriceRequest1();
            inValue.getPeriodPriceRequest = getPeriodPriceRequest;
            AgentApplication.PeriodPriceService.getPeriodPriceResponse1 retVal = ((AgentApplication.PeriodPriceService.PeriodPricePort)(this)).getPeriodPrice(inValue);
            return retVal.getPeriodPriceResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AgentApplication.PeriodPriceService.getPeriodPriceResponse1> AgentApplication.PeriodPriceService.PeriodPricePort.getPeriodPriceAsync(AgentApplication.PeriodPriceService.getPeriodPriceRequest1 request) {
            return base.Channel.getPeriodPriceAsync(request);
        }
        
        public System.Threading.Tasks.Task<AgentApplication.PeriodPriceService.getPeriodPriceResponse1> getPeriodPriceAsync(AgentApplication.PeriodPriceService.getPeriodPriceRequest getPeriodPriceRequest) {
            AgentApplication.PeriodPriceService.getPeriodPriceRequest1 inValue = new AgentApplication.PeriodPriceService.getPeriodPriceRequest1();
            inValue.getPeriodPriceRequest = getPeriodPriceRequest;
            return ((AgentApplication.PeriodPriceService.PeriodPricePort)(this)).getPeriodPriceAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AgentApplication.PeriodPriceService.getPeriodPricesResponse1 AgentApplication.PeriodPriceService.PeriodPricePort.getPeriodPrices(AgentApplication.PeriodPriceService.getPeriodPricesRequest1 request) {
            return base.Channel.getPeriodPrices(request);
        }
        
        public AgentApplication.PeriodPriceService.getPeriodPricesResponse getPeriodPrices(AgentApplication.PeriodPriceService.getPeriodPricesRequest getPeriodPricesRequest) {
            AgentApplication.PeriodPriceService.getPeriodPricesRequest1 inValue = new AgentApplication.PeriodPriceService.getPeriodPricesRequest1();
            inValue.getPeriodPricesRequest = getPeriodPricesRequest;
            AgentApplication.PeriodPriceService.getPeriodPricesResponse1 retVal = ((AgentApplication.PeriodPriceService.PeriodPricePort)(this)).getPeriodPrices(inValue);
            return retVal.getPeriodPricesResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AgentApplication.PeriodPriceService.getPeriodPricesResponse1> AgentApplication.PeriodPriceService.PeriodPricePort.getPeriodPricesAsync(AgentApplication.PeriodPriceService.getPeriodPricesRequest1 request) {
            return base.Channel.getPeriodPricesAsync(request);
        }
        
        public System.Threading.Tasks.Task<AgentApplication.PeriodPriceService.getPeriodPricesResponse1> getPeriodPricesAsync(AgentApplication.PeriodPriceService.getPeriodPricesRequest getPeriodPricesRequest) {
            AgentApplication.PeriodPriceService.getPeriodPricesRequest1 inValue = new AgentApplication.PeriodPriceService.getPeriodPricesRequest1();
            inValue.getPeriodPricesRequest = getPeriodPricesRequest;
            return ((AgentApplication.PeriodPriceService.PeriodPricePort)(this)).getPeriodPricesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AgentApplication.PeriodPriceService.addPeriodPriceResponse1 AgentApplication.PeriodPriceService.PeriodPricePort.addPeriodPrice(AgentApplication.PeriodPriceService.addPeriodPriceRequest1 request) {
            return base.Channel.addPeriodPrice(request);
        }
        
        public AgentApplication.PeriodPriceService.addPeriodPriceResponse addPeriodPrice(AgentApplication.PeriodPriceService.addPeriodPriceRequest addPeriodPriceRequest) {
            AgentApplication.PeriodPriceService.addPeriodPriceRequest1 inValue = new AgentApplication.PeriodPriceService.addPeriodPriceRequest1();
            inValue.addPeriodPriceRequest = addPeriodPriceRequest;
            AgentApplication.PeriodPriceService.addPeriodPriceResponse1 retVal = ((AgentApplication.PeriodPriceService.PeriodPricePort)(this)).addPeriodPrice(inValue);
            return retVal.addPeriodPriceResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AgentApplication.PeriodPriceService.addPeriodPriceResponse1> AgentApplication.PeriodPriceService.PeriodPricePort.addPeriodPriceAsync(AgentApplication.PeriodPriceService.addPeriodPriceRequest1 request) {
            return base.Channel.addPeriodPriceAsync(request);
        }
        
        public System.Threading.Tasks.Task<AgentApplication.PeriodPriceService.addPeriodPriceResponse1> addPeriodPriceAsync(AgentApplication.PeriodPriceService.addPeriodPriceRequest addPeriodPriceRequest) {
            AgentApplication.PeriodPriceService.addPeriodPriceRequest1 inValue = new AgentApplication.PeriodPriceService.addPeriodPriceRequest1();
            inValue.addPeriodPriceRequest = addPeriodPriceRequest;
            return ((AgentApplication.PeriodPriceService.PeriodPricePort)(this)).addPeriodPriceAsync(inValue);
        }
    }
}
