//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgentApplication.AccommodationUnitTypeService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.projectXml.com/accommmodationUnitTypes", ConfigurationName="AccommodationUnitTypeService.AccommodationUnitTypePort")]
    public interface AccommodationUnitTypePort {
        
        // CODEGEN: Generating message contract since the operation getAccommodationUnitTypes is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AgentApplication.AccommodationUnitTypeService.getAccommodationUnitTypesResponse1 getAccommodationUnitTypes(AgentApplication.AccommodationUnitTypeService.getAccommodationUnitTypesRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<AgentApplication.AccommodationUnitTypeService.getAccommodationUnitTypesResponse1> getAccommodationUnitTypesAsync(AgentApplication.AccommodationUnitTypeService.getAccommodationUnitTypesRequest1 request);
        
        // CODEGEN: Generating message contract since the operation addAccommodationUnitType is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AgentApplication.AccommodationUnitTypeService.addAccommodationUnitTypeResponse1 addAccommodationUnitType(AgentApplication.AccommodationUnitTypeService.addAccommodationUnitTypeRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<AgentApplication.AccommodationUnitTypeService.addAccommodationUnitTypeResponse1> addAccommodationUnitTypeAsync(AgentApplication.AccommodationUnitTypeService.addAccommodationUnitTypeRequest1 request);
        
        // CODEGEN: Generating message contract since the operation removeAccommodationUnitType is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void removeAccommodationUnitType(AgentApplication.AccommodationUnitTypeService.removeAccommodationUnitTypeRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="")]
        System.Threading.Tasks.Task removeAccommodationUnitTypeAsync(AgentApplication.AccommodationUnitTypeService.removeAccommodationUnitTypeRequest1 request);
        
        // CODEGEN: Generating message contract since the operation getAccommodationUnitType is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AgentApplication.AccommodationUnitTypeService.getAccommodationUnitTypeResponse1 getAccommodationUnitType(AgentApplication.AccommodationUnitTypeService.getAccommodationUnitTypeRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<AgentApplication.AccommodationUnitTypeService.getAccommodationUnitTypeResponse1> getAccommodationUnitTypeAsync(AgentApplication.AccommodationUnitTypeService.getAccommodationUnitTypeRequest1 request);
        
        // CODEGEN: Generating message contract since the operation updateAccommodationUnitType is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void updateAccommodationUnitType(AgentApplication.AccommodationUnitTypeService.updateAccommodationUnitTypeRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="")]
        System.Threading.Tasks.Task updateAccommodationUnitTypeAsync(AgentApplication.AccommodationUnitTypeService.updateAccommodationUnitTypeRequest1 request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.projectXml.com/accommodationUnitType")]
    public partial class getAccommodationUnitTypesRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.projectXml.com/accommodationUnitType")]
    public partial class accommodationUnitType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long idField;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.projectXml.com/accommodationUnitType")]
    public partial class getAccommodationUnitTypesResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private accommodationUnitType[] accommodationUnitTypesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("AccommodationUnitTypes", IsNullable=false)]
        public accommodationUnitType[] accommodationUnitTypes {
            get {
                return this.accommodationUnitTypesField;
            }
            set {
                this.accommodationUnitTypesField = value;
                this.RaisePropertyChanged("accommodationUnitTypes");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getAccommodationUnitTypesRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.projectXml.com/accommodationUnitType", Order=0)]
        public AgentApplication.AccommodationUnitTypeService.getAccommodationUnitTypesRequest getAccommodationUnitTypesRequest;
        
        public getAccommodationUnitTypesRequest1() {
        }
        
        public getAccommodationUnitTypesRequest1(AgentApplication.AccommodationUnitTypeService.getAccommodationUnitTypesRequest getAccommodationUnitTypesRequest) {
            this.getAccommodationUnitTypesRequest = getAccommodationUnitTypesRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getAccommodationUnitTypesResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.projectXml.com/accommodationUnitType", Order=0)]
        public AgentApplication.AccommodationUnitTypeService.getAccommodationUnitTypesResponse getAccommodationUnitTypesResponse;
        
        public getAccommodationUnitTypesResponse1() {
        }
        
        public getAccommodationUnitTypesResponse1(AgentApplication.AccommodationUnitTypeService.getAccommodationUnitTypesResponse getAccommodationUnitTypesResponse) {
            this.getAccommodationUnitTypesResponse = getAccommodationUnitTypesResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.projectXml.com/accommodationUnitType")]
    public partial class addAccommodationUnitTypeRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private accommodationUnitType accommodationUnitTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public accommodationUnitType accommodationUnitType {
            get {
                return this.accommodationUnitTypeField;
            }
            set {
                this.accommodationUnitTypeField = value;
                this.RaisePropertyChanged("accommodationUnitType");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.projectXml.com/accommodationUnitType")]
    public partial class addAccommodationUnitTypeResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private accommodationUnitType accommodationUnitTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public accommodationUnitType accommodationUnitType {
            get {
                return this.accommodationUnitTypeField;
            }
            set {
                this.accommodationUnitTypeField = value;
                this.RaisePropertyChanged("accommodationUnitType");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class addAccommodationUnitTypeRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.projectXml.com/accommodationUnitType", Order=0)]
        public AgentApplication.AccommodationUnitTypeService.addAccommodationUnitTypeRequest addAccommodationUnitTypeRequest;
        
        public addAccommodationUnitTypeRequest1() {
        }
        
        public addAccommodationUnitTypeRequest1(AgentApplication.AccommodationUnitTypeService.addAccommodationUnitTypeRequest addAccommodationUnitTypeRequest) {
            this.addAccommodationUnitTypeRequest = addAccommodationUnitTypeRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class addAccommodationUnitTypeResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.projectXml.com/accommodationUnitType", Order=0)]
        public AgentApplication.AccommodationUnitTypeService.addAccommodationUnitTypeResponse addAccommodationUnitTypeResponse;
        
        public addAccommodationUnitTypeResponse1() {
        }
        
        public addAccommodationUnitTypeResponse1(AgentApplication.AccommodationUnitTypeService.addAccommodationUnitTypeResponse addAccommodationUnitTypeResponse) {
            this.addAccommodationUnitTypeResponse = addAccommodationUnitTypeResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.projectXml.com/accommodationUnitType")]
    public partial class removeAccommodationUnitTypeRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long accommodationUnitTypeIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long accommodationUnitTypeId {
            get {
                return this.accommodationUnitTypeIdField;
            }
            set {
                this.accommodationUnitTypeIdField = value;
                this.RaisePropertyChanged("accommodationUnitTypeId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class removeAccommodationUnitTypeRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.projectXml.com/accommodationUnitType", Order=0)]
        public AgentApplication.AccommodationUnitTypeService.removeAccommodationUnitTypeRequest removeAccommodationUnitTypeRequest;
        
        public removeAccommodationUnitTypeRequest1() {
        }
        
        public removeAccommodationUnitTypeRequest1(AgentApplication.AccommodationUnitTypeService.removeAccommodationUnitTypeRequest removeAccommodationUnitTypeRequest) {
            this.removeAccommodationUnitTypeRequest = removeAccommodationUnitTypeRequest;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.projectXml.com/accommodationUnitType")]
    public partial class getAccommodationUnitTypeRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long accommodationUnitTypeIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long accommodationUnitTypeId {
            get {
                return this.accommodationUnitTypeIdField;
            }
            set {
                this.accommodationUnitTypeIdField = value;
                this.RaisePropertyChanged("accommodationUnitTypeId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.projectXml.com/accommodationUnitType")]
    public partial class getAccommodationUnitTypeResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private accommodationUnitType accommodationUnitTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public accommodationUnitType accommodationUnitType {
            get {
                return this.accommodationUnitTypeField;
            }
            set {
                this.accommodationUnitTypeField = value;
                this.RaisePropertyChanged("accommodationUnitType");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getAccommodationUnitTypeRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.projectXml.com/accommodationUnitType", Order=0)]
        public AgentApplication.AccommodationUnitTypeService.getAccommodationUnitTypeRequest getAccommodationUnitTypeRequest;
        
        public getAccommodationUnitTypeRequest1() {
        }
        
        public getAccommodationUnitTypeRequest1(AgentApplication.AccommodationUnitTypeService.getAccommodationUnitTypeRequest getAccommodationUnitTypeRequest) {
            this.getAccommodationUnitTypeRequest = getAccommodationUnitTypeRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getAccommodationUnitTypeResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.projectXml.com/accommodationUnitType", Order=0)]
        public AgentApplication.AccommodationUnitTypeService.getAccommodationUnitTypeResponse getAccommodationUnitTypeResponse;
        
        public getAccommodationUnitTypeResponse1() {
        }
        
        public getAccommodationUnitTypeResponse1(AgentApplication.AccommodationUnitTypeService.getAccommodationUnitTypeResponse getAccommodationUnitTypeResponse) {
            this.getAccommodationUnitTypeResponse = getAccommodationUnitTypeResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.projectXml.com/accommodationUnitType")]
    public partial class updateAccommodationUnitTypeRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private accommodationUnitType accommodationUnitTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public accommodationUnitType accommodationUnitType {
            get {
                return this.accommodationUnitTypeField;
            }
            set {
                this.accommodationUnitTypeField = value;
                this.RaisePropertyChanged("accommodationUnitType");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class updateAccommodationUnitTypeRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.projectXml.com/accommodationUnitType", Order=0)]
        public AgentApplication.AccommodationUnitTypeService.updateAccommodationUnitTypeRequest updateAccommodationUnitTypeRequest;
        
        public updateAccommodationUnitTypeRequest1() {
        }
        
        public updateAccommodationUnitTypeRequest1(AgentApplication.AccommodationUnitTypeService.updateAccommodationUnitTypeRequest updateAccommodationUnitTypeRequest) {
            this.updateAccommodationUnitTypeRequest = updateAccommodationUnitTypeRequest;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AccommodationUnitTypePortChannel : AgentApplication.AccommodationUnitTypeService.AccommodationUnitTypePort, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AccommodationUnitTypePortClient : System.ServiceModel.ClientBase<AgentApplication.AccommodationUnitTypeService.AccommodationUnitTypePort>, AgentApplication.AccommodationUnitTypeService.AccommodationUnitTypePort {
        
        public AccommodationUnitTypePortClient() {
        }
        
        public AccommodationUnitTypePortClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AccommodationUnitTypePortClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AccommodationUnitTypePortClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AccommodationUnitTypePortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AgentApplication.AccommodationUnitTypeService.getAccommodationUnitTypesResponse1 AgentApplication.AccommodationUnitTypeService.AccommodationUnitTypePort.getAccommodationUnitTypes(AgentApplication.AccommodationUnitTypeService.getAccommodationUnitTypesRequest1 request) {
            return base.Channel.getAccommodationUnitTypes(request);
        }
        
        public AgentApplication.AccommodationUnitTypeService.getAccommodationUnitTypesResponse getAccommodationUnitTypes(AgentApplication.AccommodationUnitTypeService.getAccommodationUnitTypesRequest getAccommodationUnitTypesRequest) {
            AgentApplication.AccommodationUnitTypeService.getAccommodationUnitTypesRequest1 inValue = new AgentApplication.AccommodationUnitTypeService.getAccommodationUnitTypesRequest1();
            inValue.getAccommodationUnitTypesRequest = getAccommodationUnitTypesRequest;
            AgentApplication.AccommodationUnitTypeService.getAccommodationUnitTypesResponse1 retVal = ((AgentApplication.AccommodationUnitTypeService.AccommodationUnitTypePort)(this)).getAccommodationUnitTypes(inValue);
            return retVal.getAccommodationUnitTypesResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AgentApplication.AccommodationUnitTypeService.getAccommodationUnitTypesResponse1> AgentApplication.AccommodationUnitTypeService.AccommodationUnitTypePort.getAccommodationUnitTypesAsync(AgentApplication.AccommodationUnitTypeService.getAccommodationUnitTypesRequest1 request) {
            return base.Channel.getAccommodationUnitTypesAsync(request);
        }
        
        public System.Threading.Tasks.Task<AgentApplication.AccommodationUnitTypeService.getAccommodationUnitTypesResponse1> getAccommodationUnitTypesAsync(AgentApplication.AccommodationUnitTypeService.getAccommodationUnitTypesRequest getAccommodationUnitTypesRequest) {
            AgentApplication.AccommodationUnitTypeService.getAccommodationUnitTypesRequest1 inValue = new AgentApplication.AccommodationUnitTypeService.getAccommodationUnitTypesRequest1();
            inValue.getAccommodationUnitTypesRequest = getAccommodationUnitTypesRequest;
            return ((AgentApplication.AccommodationUnitTypeService.AccommodationUnitTypePort)(this)).getAccommodationUnitTypesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AgentApplication.AccommodationUnitTypeService.addAccommodationUnitTypeResponse1 AgentApplication.AccommodationUnitTypeService.AccommodationUnitTypePort.addAccommodationUnitType(AgentApplication.AccommodationUnitTypeService.addAccommodationUnitTypeRequest1 request) {
            return base.Channel.addAccommodationUnitType(request);
        }
        
        public AgentApplication.AccommodationUnitTypeService.addAccommodationUnitTypeResponse addAccommodationUnitType(AgentApplication.AccommodationUnitTypeService.addAccommodationUnitTypeRequest addAccommodationUnitTypeRequest) {
            AgentApplication.AccommodationUnitTypeService.addAccommodationUnitTypeRequest1 inValue = new AgentApplication.AccommodationUnitTypeService.addAccommodationUnitTypeRequest1();
            inValue.addAccommodationUnitTypeRequest = addAccommodationUnitTypeRequest;
            AgentApplication.AccommodationUnitTypeService.addAccommodationUnitTypeResponse1 retVal = ((AgentApplication.AccommodationUnitTypeService.AccommodationUnitTypePort)(this)).addAccommodationUnitType(inValue);
            return retVal.addAccommodationUnitTypeResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AgentApplication.AccommodationUnitTypeService.addAccommodationUnitTypeResponse1> AgentApplication.AccommodationUnitTypeService.AccommodationUnitTypePort.addAccommodationUnitTypeAsync(AgentApplication.AccommodationUnitTypeService.addAccommodationUnitTypeRequest1 request) {
            return base.Channel.addAccommodationUnitTypeAsync(request);
        }
        
        public System.Threading.Tasks.Task<AgentApplication.AccommodationUnitTypeService.addAccommodationUnitTypeResponse1> addAccommodationUnitTypeAsync(AgentApplication.AccommodationUnitTypeService.addAccommodationUnitTypeRequest addAccommodationUnitTypeRequest) {
            AgentApplication.AccommodationUnitTypeService.addAccommodationUnitTypeRequest1 inValue = new AgentApplication.AccommodationUnitTypeService.addAccommodationUnitTypeRequest1();
            inValue.addAccommodationUnitTypeRequest = addAccommodationUnitTypeRequest;
            return ((AgentApplication.AccommodationUnitTypeService.AccommodationUnitTypePort)(this)).addAccommodationUnitTypeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void AgentApplication.AccommodationUnitTypeService.AccommodationUnitTypePort.removeAccommodationUnitType(AgentApplication.AccommodationUnitTypeService.removeAccommodationUnitTypeRequest1 request) {
            base.Channel.removeAccommodationUnitType(request);
        }
        
        public void removeAccommodationUnitType(AgentApplication.AccommodationUnitTypeService.removeAccommodationUnitTypeRequest removeAccommodationUnitTypeRequest) {
            AgentApplication.AccommodationUnitTypeService.removeAccommodationUnitTypeRequest1 inValue = new AgentApplication.AccommodationUnitTypeService.removeAccommodationUnitTypeRequest1();
            inValue.removeAccommodationUnitTypeRequest = removeAccommodationUnitTypeRequest;
            ((AgentApplication.AccommodationUnitTypeService.AccommodationUnitTypePort)(this)).removeAccommodationUnitType(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task AgentApplication.AccommodationUnitTypeService.AccommodationUnitTypePort.removeAccommodationUnitTypeAsync(AgentApplication.AccommodationUnitTypeService.removeAccommodationUnitTypeRequest1 request) {
            return base.Channel.removeAccommodationUnitTypeAsync(request);
        }
        
        public System.Threading.Tasks.Task removeAccommodationUnitTypeAsync(AgentApplication.AccommodationUnitTypeService.removeAccommodationUnitTypeRequest removeAccommodationUnitTypeRequest) {
            AgentApplication.AccommodationUnitTypeService.removeAccommodationUnitTypeRequest1 inValue = new AgentApplication.AccommodationUnitTypeService.removeAccommodationUnitTypeRequest1();
            inValue.removeAccommodationUnitTypeRequest = removeAccommodationUnitTypeRequest;
            return ((AgentApplication.AccommodationUnitTypeService.AccommodationUnitTypePort)(this)).removeAccommodationUnitTypeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AgentApplication.AccommodationUnitTypeService.getAccommodationUnitTypeResponse1 AgentApplication.AccommodationUnitTypeService.AccommodationUnitTypePort.getAccommodationUnitType(AgentApplication.AccommodationUnitTypeService.getAccommodationUnitTypeRequest1 request) {
            return base.Channel.getAccommodationUnitType(request);
        }
        
        public AgentApplication.AccommodationUnitTypeService.getAccommodationUnitTypeResponse getAccommodationUnitType(AgentApplication.AccommodationUnitTypeService.getAccommodationUnitTypeRequest getAccommodationUnitTypeRequest) {
            AgentApplication.AccommodationUnitTypeService.getAccommodationUnitTypeRequest1 inValue = new AgentApplication.AccommodationUnitTypeService.getAccommodationUnitTypeRequest1();
            inValue.getAccommodationUnitTypeRequest = getAccommodationUnitTypeRequest;
            AgentApplication.AccommodationUnitTypeService.getAccommodationUnitTypeResponse1 retVal = ((AgentApplication.AccommodationUnitTypeService.AccommodationUnitTypePort)(this)).getAccommodationUnitType(inValue);
            return retVal.getAccommodationUnitTypeResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AgentApplication.AccommodationUnitTypeService.getAccommodationUnitTypeResponse1> AgentApplication.AccommodationUnitTypeService.AccommodationUnitTypePort.getAccommodationUnitTypeAsync(AgentApplication.AccommodationUnitTypeService.getAccommodationUnitTypeRequest1 request) {
            return base.Channel.getAccommodationUnitTypeAsync(request);
        }
        
        public System.Threading.Tasks.Task<AgentApplication.AccommodationUnitTypeService.getAccommodationUnitTypeResponse1> getAccommodationUnitTypeAsync(AgentApplication.AccommodationUnitTypeService.getAccommodationUnitTypeRequest getAccommodationUnitTypeRequest) {
            AgentApplication.AccommodationUnitTypeService.getAccommodationUnitTypeRequest1 inValue = new AgentApplication.AccommodationUnitTypeService.getAccommodationUnitTypeRequest1();
            inValue.getAccommodationUnitTypeRequest = getAccommodationUnitTypeRequest;
            return ((AgentApplication.AccommodationUnitTypeService.AccommodationUnitTypePort)(this)).getAccommodationUnitTypeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void AgentApplication.AccommodationUnitTypeService.AccommodationUnitTypePort.updateAccommodationUnitType(AgentApplication.AccommodationUnitTypeService.updateAccommodationUnitTypeRequest1 request) {
            base.Channel.updateAccommodationUnitType(request);
        }
        
        public void updateAccommodationUnitType(AgentApplication.AccommodationUnitTypeService.updateAccommodationUnitTypeRequest updateAccommodationUnitTypeRequest) {
            AgentApplication.AccommodationUnitTypeService.updateAccommodationUnitTypeRequest1 inValue = new AgentApplication.AccommodationUnitTypeService.updateAccommodationUnitTypeRequest1();
            inValue.updateAccommodationUnitTypeRequest = updateAccommodationUnitTypeRequest;
            ((AgentApplication.AccommodationUnitTypeService.AccommodationUnitTypePort)(this)).updateAccommodationUnitType(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task AgentApplication.AccommodationUnitTypeService.AccommodationUnitTypePort.updateAccommodationUnitTypeAsync(AgentApplication.AccommodationUnitTypeService.updateAccommodationUnitTypeRequest1 request) {
            return base.Channel.updateAccommodationUnitTypeAsync(request);
        }
        
        public System.Threading.Tasks.Task updateAccommodationUnitTypeAsync(AgentApplication.AccommodationUnitTypeService.updateAccommodationUnitTypeRequest updateAccommodationUnitTypeRequest) {
            AgentApplication.AccommodationUnitTypeService.updateAccommodationUnitTypeRequest1 inValue = new AgentApplication.AccommodationUnitTypeService.updateAccommodationUnitTypeRequest1();
            inValue.updateAccommodationUnitTypeRequest = updateAccommodationUnitTypeRequest;
            return ((AgentApplication.AccommodationUnitTypeService.AccommodationUnitTypePort)(this)).updateAccommodationUnitTypeAsync(inValue);
        }
    }
}
