//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgentApplication.UserService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.projectXml.com/mojuser", ConfigurationName="UserService.MojuserPort")]
    public interface MojuserPort {
        
        // CODEGEN: Generating message contract since the operation unblock is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AgentApplication.UserService.unblockResponse1 unblock(AgentApplication.UserService.unblockRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<AgentApplication.UserService.unblockResponse1> unblockAsync(AgentApplication.UserService.unblockRequest1 request);
        
        // CODEGEN: Generating message contract since the operation login is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AgentApplication.UserService.loginResponse1 login(AgentApplication.UserService.loginRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<AgentApplication.UserService.loginResponse1> loginAsync(AgentApplication.UserService.loginRequest1 request);
        
        // CODEGEN: Generating message contract since the operation activate is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AgentApplication.UserService.activateResponse1 activate(AgentApplication.UserService.activateRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<AgentApplication.UserService.activateResponse1> activateAsync(AgentApplication.UserService.activateRequest1 request);
        
        // CODEGEN: Generating message contract since the operation getUserComments is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AgentApplication.UserService.getUserCommentsResponse getUserComments(AgentApplication.UserService.getUserCommentsRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<AgentApplication.UserService.getUserCommentsResponse> getUserCommentsAsync(AgentApplication.UserService.getUserCommentsRequest1 request);
        
        // CODEGEN: Generating message contract since the operation block is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AgentApplication.UserService.blockResponse1 block(AgentApplication.UserService.blockRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<AgentApplication.UserService.blockResponse1> blockAsync(AgentApplication.UserService.blockRequest1 request);
        
        // CODEGEN: Generating message contract since the operation addUser is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AgentApplication.UserService.addUserResponse1 addUser(AgentApplication.UserService.addUserRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<AgentApplication.UserService.addUserResponse1> addUserAsync(AgentApplication.UserService.addUserRequest1 request);
        
        // CODEGEN: Generating message contract since the operation delete is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AgentApplication.UserService.deleteResponse1 delete(AgentApplication.UserService.deleteRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<AgentApplication.UserService.deleteResponse1> deleteAsync(AgentApplication.UserService.deleteRequest1 request);
        
        // CODEGEN: Generating message contract since the operation getUsers is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AgentApplication.UserService.getUsersResponse getUsers(AgentApplication.UserService.getUsersRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<AgentApplication.UserService.getUsersResponse> getUsersAsync(AgentApplication.UserService.getUsersRequest1 request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.projectXml.com/mojuser")]
    public partial class unblockRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string usernameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
                this.RaisePropertyChanged("username");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.projectXml.com/mojuser")]
    public partial class comment : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string contentOfCommentField;
        
        private bool approvedCommentField;
        
        private long idReservationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string contentOfComment {
            get {
                return this.contentOfCommentField;
            }
            set {
                this.contentOfCommentField = value;
                this.RaisePropertyChanged("contentOfComment");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public bool approvedComment {
            get {
                return this.approvedCommentField;
            }
            set {
                this.approvedCommentField = value;
                this.RaisePropertyChanged("approvedComment");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public long idReservation {
            get {
                return this.idReservationField;
            }
            set {
                this.idReservationField = value;
                this.RaisePropertyChanged("idReservation");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.projectXml.com/mojuser")]
    public partial class Address : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string countryField;
        
        private string cityField;
        
        private int postal_codeField;
        
        private string streetField;
        
        private string numberField;
        
        private string apartment_numberField;
        
        private double longitudeField;
        
        private double latitudeField;
        
        private long idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
                this.RaisePropertyChanged("Country");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
                this.RaisePropertyChanged("City");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int Postal_code {
            get {
                return this.postal_codeField;
            }
            set {
                this.postal_codeField = value;
                this.RaisePropertyChanged("Postal_code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Street {
            get {
                return this.streetField;
            }
            set {
                this.streetField = value;
                this.RaisePropertyChanged("Street");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Number {
            get {
                return this.numberField;
            }
            set {
                this.numberField = value;
                this.RaisePropertyChanged("Number");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Apartment_number {
            get {
                return this.apartment_numberField;
            }
            set {
                this.apartment_numberField = value;
                this.RaisePropertyChanged("Apartment_number");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public double Longitude {
            get {
                return this.longitudeField;
            }
            set {
                this.longitudeField = value;
                this.RaisePropertyChanged("Longitude");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public double Latitude {
            get {
                return this.latitudeField;
            }
            set {
                this.latitudeField = value;
                this.RaisePropertyChanged("Latitude");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public long Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.projectXml.com/mojuser")]
    public partial class user : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nameField;
        
        private string lastnameField;
        
        private string emailField;
        
        private string usernameField;
        
        private string passwordField;
        
        private long idField;
        
        private bool enabledField;
        
        private bool deletedField;
        
        private string roleField;
        
        private Address addressField;
        
        private long bussines_registration_numberField;
        
        private bool blockedField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Lastname {
            get {
                return this.lastnameField;
            }
            set {
                this.lastnameField = value;
                this.RaisePropertyChanged("Lastname");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
                this.RaisePropertyChanged("Email");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
                this.RaisePropertyChanged("Username");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("Password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public long Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public bool Enabled {
            get {
                return this.enabledField;
            }
            set {
                this.enabledField = value;
                this.RaisePropertyChanged("Enabled");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public bool Deleted {
            get {
                return this.deletedField;
            }
            set {
                this.deletedField = value;
                this.RaisePropertyChanged("Deleted");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string Role {
            get {
                return this.roleField;
            }
            set {
                this.roleField = value;
                this.RaisePropertyChanged("Role");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public Address Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
                this.RaisePropertyChanged("Address");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public long Bussines_registration_number {
            get {
                return this.bussines_registration_numberField;
            }
            set {
                this.bussines_registration_numberField = value;
                this.RaisePropertyChanged("Bussines_registration_number");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public bool Blocked {
            get {
                return this.blockedField;
            }
            set {
                this.blockedField = value;
                this.RaisePropertyChanged("Blocked");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.projectXml.com/mojuser")]
    public partial class LoginDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string usernameField;
        
        private string passwordField;
        
        private string roleField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
                this.RaisePropertyChanged("username");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string role {
            get {
                return this.roleField;
            }
            set {
                this.roleField = value;
                this.RaisePropertyChanged("role");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.projectXml.com/mojuser")]
    public partial class unblockResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool successField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
                this.RaisePropertyChanged("success");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class unblockRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.projectXml.com/mojuser", Order=0)]
        public AgentApplication.UserService.unblockRequest unblockRequest;
        
        public unblockRequest1() {
        }
        
        public unblockRequest1(AgentApplication.UserService.unblockRequest unblockRequest) {
            this.unblockRequest = unblockRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class unblockResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.projectXml.com/mojuser", Order=0)]
        public AgentApplication.UserService.unblockResponse unblockResponse;
        
        public unblockResponse1() {
        }
        
        public unblockResponse1(AgentApplication.UserService.unblockResponse unblockResponse) {
            this.unblockResponse = unblockResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.projectXml.com/mojuser")]
    public partial class loginRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private LoginDTO loginDTOField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public LoginDTO loginDTO {
            get {
                return this.loginDTOField;
            }
            set {
                this.loginDTOField = value;
                this.RaisePropertyChanged("loginDTO");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.projectXml.com/mojuser")]
    public partial class loginResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private user userField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public user user {
            get {
                return this.userField;
            }
            set {
                this.userField = value;
                this.RaisePropertyChanged("user");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class loginRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.projectXml.com/mojuser", Order=0)]
        public AgentApplication.UserService.loginRequest loginRequest;
        
        public loginRequest1() {
        }
        
        public loginRequest1(AgentApplication.UserService.loginRequest loginRequest) {
            this.loginRequest = loginRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class loginResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.projectXml.com/mojuser", Order=0)]
        public AgentApplication.UserService.loginResponse loginResponse;
        
        public loginResponse1() {
        }
        
        public loginResponse1(AgentApplication.UserService.loginResponse loginResponse) {
            this.loginResponse = loginResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.projectXml.com/mojuser")]
    public partial class activateRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.projectXml.com/mojuser")]
    public partial class activateResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool successField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
                this.RaisePropertyChanged("success");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class activateRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.projectXml.com/mojuser", Order=0)]
        public AgentApplication.UserService.activateRequest activateRequest;
        
        public activateRequest1() {
        }
        
        public activateRequest1(AgentApplication.UserService.activateRequest activateRequest) {
            this.activateRequest = activateRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class activateResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.projectXml.com/mojuser", Order=0)]
        public AgentApplication.UserService.activateResponse activateResponse;
        
        public activateResponse1() {
        }
        
        public activateResponse1(AgentApplication.UserService.activateResponse activateResponse) {
            this.activateResponse = activateResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.projectXml.com/mojuser")]
    public partial class getUserCommentsRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string usernameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
                this.RaisePropertyChanged("username");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getUserCommentsRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.projectXml.com/mojuser", Order=0)]
        public AgentApplication.UserService.getUserCommentsRequest getUserCommentsRequest;
        
        public getUserCommentsRequest1() {
        }
        
        public getUserCommentsRequest1(AgentApplication.UserService.getUserCommentsRequest getUserCommentsRequest) {
            this.getUserCommentsRequest = getUserCommentsRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getUserCommentsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getUserCommentsResponse", Namespace="http://www.projectXml.com/mojuser", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("comments", IsNullable=false)]
        public AgentApplication.UserService.comment[] getUserCommentsResponse1;
        
        public getUserCommentsResponse() {
        }
        
        public getUserCommentsResponse(AgentApplication.UserService.comment[] getUserCommentsResponse1) {
            this.getUserCommentsResponse1 = getUserCommentsResponse1;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.projectXml.com/mojuser")]
    public partial class blockRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string usernameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
                this.RaisePropertyChanged("username");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.projectXml.com/mojuser")]
    public partial class blockResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool successField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
                this.RaisePropertyChanged("success");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class blockRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.projectXml.com/mojuser", Order=0)]
        public AgentApplication.UserService.blockRequest blockRequest;
        
        public blockRequest1() {
        }
        
        public blockRequest1(AgentApplication.UserService.blockRequest blockRequest) {
            this.blockRequest = blockRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class blockResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.projectXml.com/mojuser", Order=0)]
        public AgentApplication.UserService.blockResponse blockResponse;
        
        public blockResponse1() {
        }
        
        public blockResponse1(AgentApplication.UserService.blockResponse blockResponse) {
            this.blockResponse = blockResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.projectXml.com/mojuser")]
    public partial class addUserRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private user userField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public user user {
            get {
                return this.userField;
            }
            set {
                this.userField = value;
                this.RaisePropertyChanged("user");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.projectXml.com/mojuser")]
    public partial class addUserResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool successField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
                this.RaisePropertyChanged("success");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class addUserRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.projectXml.com/mojuser", Order=0)]
        public AgentApplication.UserService.addUserRequest addUserRequest;
        
        public addUserRequest1() {
        }
        
        public addUserRequest1(AgentApplication.UserService.addUserRequest addUserRequest) {
            this.addUserRequest = addUserRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class addUserResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.projectXml.com/mojuser", Order=0)]
        public AgentApplication.UserService.addUserResponse addUserResponse;
        
        public addUserResponse1() {
        }
        
        public addUserResponse1(AgentApplication.UserService.addUserResponse addUserResponse) {
            this.addUserResponse = addUserResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.projectXml.com/mojuser")]
    public partial class deleteRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string usernameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
                this.RaisePropertyChanged("username");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.projectXml.com/mojuser")]
    public partial class deleteResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool successField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
                this.RaisePropertyChanged("success");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class deleteRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.projectXml.com/mojuser", Order=0)]
        public AgentApplication.UserService.deleteRequest deleteRequest;
        
        public deleteRequest1() {
        }
        
        public deleteRequest1(AgentApplication.UserService.deleteRequest deleteRequest) {
            this.deleteRequest = deleteRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class deleteResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.projectXml.com/mojuser", Order=0)]
        public AgentApplication.UserService.deleteResponse deleteResponse;
        
        public deleteResponse1() {
        }
        
        public deleteResponse1(AgentApplication.UserService.deleteResponse deleteResponse) {
            this.deleteResponse = deleteResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.projectXml.com/mojuser")]
    public partial class getUsersRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string usernameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
                this.RaisePropertyChanged("username");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getUsersRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.projectXml.com/mojuser", Order=0)]
        public AgentApplication.UserService.getUsersRequest getUsersRequest;
        
        public getUsersRequest1() {
        }
        
        public getUsersRequest1(AgentApplication.UserService.getUsersRequest getUsersRequest) {
            this.getUsersRequest = getUsersRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getUsersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getUsersResponse", Namespace="http://www.projectXml.com/mojuser", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public AgentApplication.UserService.user[] getUsersResponse1;
        
        public getUsersResponse() {
        }
        
        public getUsersResponse(AgentApplication.UserService.user[] getUsersResponse1) {
            this.getUsersResponse1 = getUsersResponse1;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MojuserPortChannel : AgentApplication.UserService.MojuserPort, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MojuserPortClient : System.ServiceModel.ClientBase<AgentApplication.UserService.MojuserPort>, AgentApplication.UserService.MojuserPort {
        
        public MojuserPortClient() {
        }
        
        public MojuserPortClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MojuserPortClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MojuserPortClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MojuserPortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AgentApplication.UserService.unblockResponse1 AgentApplication.UserService.MojuserPort.unblock(AgentApplication.UserService.unblockRequest1 request) {
            return base.Channel.unblock(request);
        }
        
        public AgentApplication.UserService.unblockResponse unblock(AgentApplication.UserService.unblockRequest unblockRequest) {
            AgentApplication.UserService.unblockRequest1 inValue = new AgentApplication.UserService.unblockRequest1();
            inValue.unblockRequest = unblockRequest;
            AgentApplication.UserService.unblockResponse1 retVal = ((AgentApplication.UserService.MojuserPort)(this)).unblock(inValue);
            return retVal.unblockResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AgentApplication.UserService.unblockResponse1> AgentApplication.UserService.MojuserPort.unblockAsync(AgentApplication.UserService.unblockRequest1 request) {
            return base.Channel.unblockAsync(request);
        }
        
        public System.Threading.Tasks.Task<AgentApplication.UserService.unblockResponse1> unblockAsync(AgentApplication.UserService.unblockRequest unblockRequest) {
            AgentApplication.UserService.unblockRequest1 inValue = new AgentApplication.UserService.unblockRequest1();
            inValue.unblockRequest = unblockRequest;
            return ((AgentApplication.UserService.MojuserPort)(this)).unblockAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AgentApplication.UserService.loginResponse1 AgentApplication.UserService.MojuserPort.login(AgentApplication.UserService.loginRequest1 request) {
            return base.Channel.login(request);
        }
        
        public AgentApplication.UserService.loginResponse login(AgentApplication.UserService.loginRequest loginRequest) {
            AgentApplication.UserService.loginRequest1 inValue = new AgentApplication.UserService.loginRequest1();
            inValue.loginRequest = loginRequest;
            AgentApplication.UserService.loginResponse1 retVal = ((AgentApplication.UserService.MojuserPort)(this)).login(inValue);
            return retVal.loginResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AgentApplication.UserService.loginResponse1> AgentApplication.UserService.MojuserPort.loginAsync(AgentApplication.UserService.loginRequest1 request) {
            return base.Channel.loginAsync(request);
        }
        
        public System.Threading.Tasks.Task<AgentApplication.UserService.loginResponse1> loginAsync(AgentApplication.UserService.loginRequest loginRequest) {
            AgentApplication.UserService.loginRequest1 inValue = new AgentApplication.UserService.loginRequest1();
            inValue.loginRequest = loginRequest;
            return ((AgentApplication.UserService.MojuserPort)(this)).loginAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AgentApplication.UserService.activateResponse1 AgentApplication.UserService.MojuserPort.activate(AgentApplication.UserService.activateRequest1 request) {
            return base.Channel.activate(request);
        }
        
        public AgentApplication.UserService.activateResponse activate(AgentApplication.UserService.activateRequest activateRequest) {
            AgentApplication.UserService.activateRequest1 inValue = new AgentApplication.UserService.activateRequest1();
            inValue.activateRequest = activateRequest;
            AgentApplication.UserService.activateResponse1 retVal = ((AgentApplication.UserService.MojuserPort)(this)).activate(inValue);
            return retVal.activateResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AgentApplication.UserService.activateResponse1> AgentApplication.UserService.MojuserPort.activateAsync(AgentApplication.UserService.activateRequest1 request) {
            return base.Channel.activateAsync(request);
        }
        
        public System.Threading.Tasks.Task<AgentApplication.UserService.activateResponse1> activateAsync(AgentApplication.UserService.activateRequest activateRequest) {
            AgentApplication.UserService.activateRequest1 inValue = new AgentApplication.UserService.activateRequest1();
            inValue.activateRequest = activateRequest;
            return ((AgentApplication.UserService.MojuserPort)(this)).activateAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AgentApplication.UserService.getUserCommentsResponse AgentApplication.UserService.MojuserPort.getUserComments(AgentApplication.UserService.getUserCommentsRequest1 request) {
            return base.Channel.getUserComments(request);
        }
        
        public AgentApplication.UserService.comment[] getUserComments(AgentApplication.UserService.getUserCommentsRequest getUserCommentsRequest) {
            AgentApplication.UserService.getUserCommentsRequest1 inValue = new AgentApplication.UserService.getUserCommentsRequest1();
            inValue.getUserCommentsRequest = getUserCommentsRequest;
            AgentApplication.UserService.getUserCommentsResponse retVal = ((AgentApplication.UserService.MojuserPort)(this)).getUserComments(inValue);
            return retVal.getUserCommentsResponse1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AgentApplication.UserService.getUserCommentsResponse> AgentApplication.UserService.MojuserPort.getUserCommentsAsync(AgentApplication.UserService.getUserCommentsRequest1 request) {
            return base.Channel.getUserCommentsAsync(request);
        }
        
        public System.Threading.Tasks.Task<AgentApplication.UserService.getUserCommentsResponse> getUserCommentsAsync(AgentApplication.UserService.getUserCommentsRequest getUserCommentsRequest) {
            AgentApplication.UserService.getUserCommentsRequest1 inValue = new AgentApplication.UserService.getUserCommentsRequest1();
            inValue.getUserCommentsRequest = getUserCommentsRequest;
            return ((AgentApplication.UserService.MojuserPort)(this)).getUserCommentsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AgentApplication.UserService.blockResponse1 AgentApplication.UserService.MojuserPort.block(AgentApplication.UserService.blockRequest1 request) {
            return base.Channel.block(request);
        }
        
        public AgentApplication.UserService.blockResponse block(AgentApplication.UserService.blockRequest blockRequest) {
            AgentApplication.UserService.blockRequest1 inValue = new AgentApplication.UserService.blockRequest1();
            inValue.blockRequest = blockRequest;
            AgentApplication.UserService.blockResponse1 retVal = ((AgentApplication.UserService.MojuserPort)(this)).block(inValue);
            return retVal.blockResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AgentApplication.UserService.blockResponse1> AgentApplication.UserService.MojuserPort.blockAsync(AgentApplication.UserService.blockRequest1 request) {
            return base.Channel.blockAsync(request);
        }
        
        public System.Threading.Tasks.Task<AgentApplication.UserService.blockResponse1> blockAsync(AgentApplication.UserService.blockRequest blockRequest) {
            AgentApplication.UserService.blockRequest1 inValue = new AgentApplication.UserService.blockRequest1();
            inValue.blockRequest = blockRequest;
            return ((AgentApplication.UserService.MojuserPort)(this)).blockAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AgentApplication.UserService.addUserResponse1 AgentApplication.UserService.MojuserPort.addUser(AgentApplication.UserService.addUserRequest1 request) {
            return base.Channel.addUser(request);
        }
        
        public AgentApplication.UserService.addUserResponse addUser(AgentApplication.UserService.addUserRequest addUserRequest) {
            AgentApplication.UserService.addUserRequest1 inValue = new AgentApplication.UserService.addUserRequest1();
            inValue.addUserRequest = addUserRequest;
            AgentApplication.UserService.addUserResponse1 retVal = ((AgentApplication.UserService.MojuserPort)(this)).addUser(inValue);
            return retVal.addUserResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AgentApplication.UserService.addUserResponse1> AgentApplication.UserService.MojuserPort.addUserAsync(AgentApplication.UserService.addUserRequest1 request) {
            return base.Channel.addUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<AgentApplication.UserService.addUserResponse1> addUserAsync(AgentApplication.UserService.addUserRequest addUserRequest) {
            AgentApplication.UserService.addUserRequest1 inValue = new AgentApplication.UserService.addUserRequest1();
            inValue.addUserRequest = addUserRequest;
            return ((AgentApplication.UserService.MojuserPort)(this)).addUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AgentApplication.UserService.deleteResponse1 AgentApplication.UserService.MojuserPort.delete(AgentApplication.UserService.deleteRequest1 request) {
            return base.Channel.delete(request);
        }
        
        public AgentApplication.UserService.deleteResponse delete(AgentApplication.UserService.deleteRequest deleteRequest) {
            AgentApplication.UserService.deleteRequest1 inValue = new AgentApplication.UserService.deleteRequest1();
            inValue.deleteRequest = deleteRequest;
            AgentApplication.UserService.deleteResponse1 retVal = ((AgentApplication.UserService.MojuserPort)(this)).delete(inValue);
            return retVal.deleteResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AgentApplication.UserService.deleteResponse1> AgentApplication.UserService.MojuserPort.deleteAsync(AgentApplication.UserService.deleteRequest1 request) {
            return base.Channel.deleteAsync(request);
        }
        
        public System.Threading.Tasks.Task<AgentApplication.UserService.deleteResponse1> deleteAsync(AgentApplication.UserService.deleteRequest deleteRequest) {
            AgentApplication.UserService.deleteRequest1 inValue = new AgentApplication.UserService.deleteRequest1();
            inValue.deleteRequest = deleteRequest;
            return ((AgentApplication.UserService.MojuserPort)(this)).deleteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AgentApplication.UserService.getUsersResponse AgentApplication.UserService.MojuserPort.getUsers(AgentApplication.UserService.getUsersRequest1 request) {
            return base.Channel.getUsers(request);
        }
        
        public AgentApplication.UserService.user[] getUsers(AgentApplication.UserService.getUsersRequest getUsersRequest) {
            AgentApplication.UserService.getUsersRequest1 inValue = new AgentApplication.UserService.getUsersRequest1();
            inValue.getUsersRequest = getUsersRequest;
            AgentApplication.UserService.getUsersResponse retVal = ((AgentApplication.UserService.MojuserPort)(this)).getUsers(inValue);
            return retVal.getUsersResponse1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AgentApplication.UserService.getUsersResponse> AgentApplication.UserService.MojuserPort.getUsersAsync(AgentApplication.UserService.getUsersRequest1 request) {
            return base.Channel.getUsersAsync(request);
        }
        
        public System.Threading.Tasks.Task<AgentApplication.UserService.getUsersResponse> getUsersAsync(AgentApplication.UserService.getUsersRequest getUsersRequest) {
            AgentApplication.UserService.getUsersRequest1 inValue = new AgentApplication.UserService.getUsersRequest1();
            inValue.getUsersRequest = getUsersRequest;
            return ((AgentApplication.UserService.MojuserPort)(this)).getUsersAsync(inValue);
        }
    }
}
